# Generated by Django 3.0.8 on 2020-07-07 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default=datetime.datetime(2020, 7, 7, 7, 47, 58, 701683, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
